-- WORK-027: Execution provider abstraction persistence.
--
-- Three tables:
--   1. wfos_executions          — one row per Work Order execution submission
--                                 (native via AgentGateway, or external handoff).
--   2. wfos_execution_events    — ingested external execution events
--                                 (started/progress/completed/failed). Never
--                                 mutates workflow state.
--   3. wfos_execution_handoffs  — one-time, short-lived handoff tokens used to
--                                 retrieve an ExternalExecutionPackage. Only the
--                                 SHA-256 hash of the raw token is persisted.
--
-- Execution state is SEPARATE from the canonical Work Item workflow state
-- (owned by /workflows via wfos_workflow_executions). External execution can
-- never declare MERGED / VERIFIED / PASS / APPROVED — WorkflowOS observes
-- authoritative GitHub/CI/verification/review state instead.

CREATE TABLE IF NOT EXISTS wfos_executions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  execution_id TEXT NOT NULL UNIQUE,
  project_id UUID NOT NULL REFERENCES wfos_projects(id) ON DELETE CASCADE,
  work_item_id UUID NOT NULL REFERENCES wfos_work_items(id) ON DELETE CASCADE,
  work_order_id UUID NOT NULL REFERENCES wfos_work_orders(id) ON DELETE CASCADE,
  implementation_context_id UUID NOT NULL REFERENCES wfos_implementation_contexts(id) ON DELETE CASCADE,
  mode TEXT NOT NULL CHECK (mode IN ('native', 'external')),
  provider TEXT NOT NULL,
  model TEXT,
  -- Execution-level state machine (NOT the Work Item workflow state machine).
  status TEXT NOT NULL DEFAULT 'created' CHECK (status IN (
    'created', 'queued', 'running', 'handoff_ready', 'submitted',
    'completed', 'failed', 'cancelled', 'expired')),
  agent_run_id UUID,
  external_session_ref TEXT,
  repository_ref TEXT,
  branch TEXT,
  -- Deterministic implementation prompt (benchmark foundation). The prompt is
  -- generated by WorkflowOS from the persisted ImplementationContext and
  -- contains NO secrets.
  prompt TEXT NOT NULL DEFAULT '',
  prompt_digest TEXT NOT NULL DEFAULT '',
  -- ExternalExecutionPackage JSON (external mode only; safe metadata + prompt).
  package_json JSONB,
  -- Benchmark metadata (WORK-027 foundation; enriched by ingested events).
  benchmark_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_executions_work_item
  ON wfos_executions(work_item_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_executions_project
  ON wfos_executions(project_id, created_at DESC);

-- Cross-tenant guard: the execution must reference resources that all belong
-- to the same project (mirrors the wfos_work_orders integrity trigger — the
-- project is resolved via work item → architecture version → architecture).
CREATE OR REPLACE FUNCTION wfos_executions_integrity_check() RETURNS trigger AS $$
DECLARE
  wi_version UUID;
  wi_project UUID;
  wo_work_item UUID;
  ctx_work_item UUID;
BEGIN
  SELECT architecture_version_id INTO wi_version FROM wfos_work_items WHERE id = NEW.work_item_id;
  IF wi_version IS NULL THEN
    RAISE EXCEPTION 'execution integrity: work item % not found', NEW.work_item_id;
  END IF;
  SELECT a.project_id INTO wi_project
    FROM wfos_architecture_versions v
    JOIN wfos_architectures a ON a.id = v.architecture_id
    WHERE v.id = wi_version;
  IF wi_project IS NULL OR wi_project <> NEW.project_id THEN
    RAISE EXCEPTION 'execution project mismatch for work item %', NEW.work_item_id;
  END IF;
  SELECT work_item_id INTO wo_work_item FROM wfos_work_orders WHERE id = NEW.work_order_id;
  IF wo_work_item IS NULL OR wo_work_item <> NEW.work_item_id THEN
    RAISE EXCEPTION 'execution work order % does not belong to work item %', NEW.work_order_id, NEW.work_item_id;
  END IF;
  SELECT work_item_id INTO ctx_work_item FROM wfos_implementation_contexts WHERE id = NEW.implementation_context_id;
  IF ctx_work_item IS NULL OR ctx_work_item <> NEW.work_item_id THEN
    RAISE EXCEPTION 'execution implementation context % does not belong to work item %', NEW.implementation_context_id, NEW.work_item_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS wfos_executions_integrity_check_trigger ON wfos_executions;
CREATE TRIGGER wfos_executions_integrity_check_trigger
  BEFORE INSERT ON wfos_executions
  FOR EACH ROW EXECUTE FUNCTION wfos_executions_integrity_check();

CREATE TABLE IF NOT EXISTS wfos_execution_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  execution_record_id UUID NOT NULL REFERENCES wfos_executions(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL CHECK (event_type IN ('started', 'progress', 'completed', 'failed')),
  commit_ref TEXT,
  branch TEXT,
  pull_request_ref TEXT,
  test_summary JSONB,
  output TEXT,
  external_session_ref TEXT,
  idempotency_key TEXT,
  received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_execution_events_record
  ON wfos_execution_events(execution_record_id, received_at ASC);

CREATE TABLE IF NOT EXISTS wfos_execution_handoffs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  execution_record_id UUID NOT NULL REFERENCES wfos_executions(id) ON DELETE CASCADE,
  -- SHA-256 hex of the raw handoff token. The raw token is returned to the
  -- authorized caller exactly once and is never persisted or logged.
  token_hash TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  consumed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_execution_handoffs_record
  ON wfos_execution_handoffs(execution_record_id, created_at DESC);
