/**
 * WORK-025: Conversational Architect types.
 *
 * Extends the existing /llm Architect types to support a conversational
 * architecture workspace where the user iterates with the Architect LLM
 * until the architecture is satisfactory.
 *
 * The /llm module owns these types + the session/revision persistence.
 */

/** A single message in the Architect conversation. */
export interface ArchitectMessage {
  readonly role: 'user' | 'assistant';
  readonly content: string;
  readonly timestamp: string;
}

/** A revision of the generated architecture plan. */
export interface ArchitectRevision {
  readonly id: string;
  readonly sessionId: string;
  readonly revisionNumber: number;
  readonly userPrompt: string;
  readonly architectResponse: string;
  readonly parsedPlan: ArchitectParsedPlan | null;
  readonly createdAt: string;
}

/** The structured plan generated by the Architect. */
export interface ArchitectParsedPlan {
  architecture?: {
    name: string;
    content: string;
    constraints?: string[];
  };
  requirements?: Array<{
    requirementId: string;
    title: string;
    description?: string;
    criteria?: Array<{ criterionId: string; description: string }>;
  }>;
  workItems?: Array<{
    workItemId: string;
    title: string;
    objective?: string;
    scope?: string;
    requirementIds?: string[];
    criterionIds?: string[];
    dependencies?: string[];
  }>;
  summary?: string;
}

/** An active Architect conversation session. */
export interface ArchitectSession {
  readonly id: string;
  readonly projectId: string;
  readonly status: 'active' | 'accepted' | 'abandoned';
  readonly provider: string;
  readonly model: string;
  readonly messages: ArchitectMessage[];
  readonly revisionCount: number;
  readonly createdAt: string;
  readonly updatedAt: string;
}

/** Repository for Architect session/revision persistence. */
export interface ArchitectSessionRepository {
  /** Find the active session for a project (or null). */
  findActiveByProject(projectId: string): Promise<ArchitectSession | null>;

  /** Create a new session. */
  create(input: {
    projectId: string;
    provider: string;
    model: string;
  }): Promise<ArchitectSession>;

  /** Update the session's messages + last parsed plan. */
  updateMessages(
    sessionId: string,
    messages: ArchitectMessage[],
    parsedPlan: ArchitectParsedPlan | null,
  ): Promise<void>;

  /** Save a revision (immutable history entry). */
  saveRevision(input: {
    sessionId: string;
    revisionNumber: number;
    userPrompt: string;
    architectResponse: string;
    parsedPlan: ArchitectParsedPlan | null;
  }): Promise<ArchitectRevision>;

  /** List all revisions for a session (for diff/history view). */
  listRevisions(sessionId: string): Promise<ArchitectRevision[]>;

  /** Mark session as accepted. */
  markAccepted(sessionId: string): Promise<void>;
}

/** Result of a conversational architect execution. */
export interface ConversationalArchitectResult {
  readonly executionId: string;
  readonly content: string;
  readonly parsedPlan: ArchitectParsedPlan | null;
  readonly usage: {
    promptTokens: number | null;
    completionTokens: number | null;
    totalTokens: number | null;
  };
}

/** Provider configuration (no secrets — readiness only). */
export interface ProviderConfig {
  readonly name: string;
  readonly provider: string;
  readonly model: string;
  readonly status: 'ready' | 'not-configured';
}

/** Service for the conversational Architect workspace. */
export interface ConversationalArchitectService {
  /**
   * Send a user prompt + conversation history to the LLM and get a structured
   * architecture proposal back. Uses the existing LlmGateway (not a second
   * LLM implementation). The service assembles authoritative project context
   * (architecture, requirements, etc.) and includes it in the prompt.
   */
  converse(input: {
    projectId: string;
    prompt: string;
    conversation: ArchitectMessage[];
    provider: string;
    model: string;
  }): Promise<ConversationalArchitectResult>;

  /**
   * Get available provider configurations (readiness only — no secrets).
   */
  getProviders(): ProviderConfig[];
}
