/**
 * WORK-027: DefaultExecutionTaskService.
 *
 * Constructs the provider-independent ExecutionTask from AUTHORITATIVE,
 * PERSISTED WorkflowOS data:
 *
 *   1. Load the Work Item (throw if missing).
 *   2. Load the latest Work Order (throw if none — the executions table has a
 *      NOT NULL work_order FK, same policy as wfos_agent_runs).
 *   3. Build + persist the ImplementationContext via the EXISTING
 *      DefaultImplementationContextBuilder (the context authority) — unless
 *      the caller already built one this request (reuse by id, no double
 *      revision bump).
 *   4. Resolve the project id (Work Item → ArchitectureVersion →
 *      Architecture → project).
 *   5. Generate the deterministic implementation prompt via the
 *      ExecutionPromptBuilder.
 *   6. Assemble the ExecutionTask (consumed by /agents ExecutionService).
 *
 * The service never mutates workflow state and never talks to providers.
 *
 * This file is private to /work-items (PLAT-AC-02). It imports ExecutionTask
 * from the /agents PUBLIC barrel (same precedent as start-implementation-service
 * importing AgentGateway).
 */
import type {
  ExecutionMode,
  ExecutionTask,
} from '@modules/agents/index.js';
import type { Logger } from '@platform/logger.js';
import type {
  WorkItemRepository,
  WorkOrderRepository,
} from './work-item.types.js';
import type {
  ImplementationContext,
  ImplementationContextBuilder,
} from './implementation-context.types.js';
import type { ExecutionPromptBuilder } from './execution-prompt-builder.js';
import type { ArchitectureRepository, ArchitectureVersionRepository } from '@modules/architecture/index.js';

export interface ExecutionTaskServiceInput {
  readonly workItemId: string;
  readonly mode: ExecutionMode;
  /** Validated provider (validated against the registry by the route). */
  readonly provider: string;
  /** Model — required for native mode, optional for external. */
  readonly model: string | null;
  /** Traceable execution id (generated by the route). */
  readonly executionId: string;
  /**
   * Optional: reuse an ImplementationContext built earlier in the same
   * request (the start-implementation route builds it before calling the
   * service). When omitted, a fresh context revision is built + persisted.
   */
  readonly implementationContextId?: string;
}

export interface BuiltExecutionTask {
  readonly task: ExecutionTask;
  readonly implementationContext: Pick<
    ImplementationContext,
    'id' | 'revision' | 'kind'
  >;
}

export interface ExecutionTaskService {
  build(input: ExecutionTaskServiceInput): Promise<BuiltExecutionTask>;
}

export interface DefaultExecutionTaskServiceDeps {
  readonly workItemRepository: WorkItemRepository;
  readonly workOrderRepository: WorkOrderRepository;
  readonly architectureVersionRepository: ArchitectureVersionRepository;
  readonly architectureRepository: ArchitectureRepository;
  readonly implementationContextBuilder: ImplementationContextBuilder;
  readonly contextRepository: {
    findById(id: string): Promise<ImplementationContext | null>;
  };
  readonly promptBuilder: ExecutionPromptBuilder;
  readonly logger: Logger;
}

export class DefaultExecutionTaskService implements ExecutionTaskService {
  constructor(private readonly deps: DefaultExecutionTaskServiceDeps) {}

  async build(input: ExecutionTaskServiceInput): Promise<BuiltExecutionTask> {
    // 1. Work Item.
    const workItem = await this.deps.workItemRepository.findById(input.workItemId);
    if (!workItem) {
      throw new Error(`start-implementation-work-item-not-found: ${input.workItemId}`);
    }

    // 2. Latest Work Order (work_order FK is NOT NULL).
    const workOrders = await this.deps.workOrderRepository.listForWorkItem(input.workItemId);
    const workOrder = workOrders.length > 0 ? workOrders[workOrders.length - 1]! : null;
    if (!workOrder) {
      throw new Error(
        `start-implementation-work-order-not-found: work item ${input.workItemId} has no Work Order. ` +
          'Generate a Work Order before starting implementation.',
      );
    }

    // 3. ImplementationContext — reuse when provided, else build fresh.
    let ctx: ImplementationContext | null = input.implementationContextId
      ? await this.deps.contextRepository.findById(input.implementationContextId)
      : null;
    if (input.implementationContextId && !ctx) {
      throw new Error(
        `start-implementation-context-not-found: ${input.implementationContextId}`,
      );
    }
    if (!ctx) {
      ctx = await this.deps.implementationContextBuilder.build(input.workItemId);
    }

    // 4. Resolve the project (Work Item → version → architecture → project).
    const version = workItem.architectureVersionId
      ? await this.deps.architectureVersionRepository.findById(workItem.architectureVersionId)
      : null;
    if (!version) {
      throw new Error(
        `execution-task-architecture-version-not-found: ${workItem.architectureVersionId}`,
      );
    }
    const architecture = await this.deps.architectureRepository.findById(version.architectureId);
    if (!architecture) {
      throw new Error(
        `execution-task-architecture-not-found: ${version.architectureId}`,
      );
    }

    // 5. Deterministic prompt (pure function of the persisted content).
    const prompt = this.deps.promptBuilder.build(ctx.content, {
      workItemLabel: workItem.workItemId,
    });

    const repository = ctx.content.repository;

    const task: ExecutionTask = {
      executionId: input.executionId,
      mode: input.mode,
      provider: input.provider,
      model: input.model,
      projectId: architecture.projectId,
      workItemId: workItem.id,
      workItemLabel: workItem.workItemId,
      workOrderId: workOrder.id,
      architectureVersionId: workItem.architectureVersionId,
      implementationContextId: ctx.id,
      implementationContextRevision: ctx.revision,
      implementationContextKind: ctx.kind,
      repositoryOwner: repository?.owner ?? null,
      repositoryName: repository?.repository ?? null,
      repositoryDefaultBranch: repository?.defaultBranch ?? null,
      implementationBranch: repository?.implementationBranch ?? null,
      scope: ctx.content.scope ?? null,
      expectedOutputs: ctx.content.expectedTests,
      verificationRequirements: ctx.content.verificationRequirements,
      architectureConstraints: ctx.content.architectureConstraints ?? null,
      prompt: prompt.markdown,
      promptDigest: prompt.digest,
      // Native agent input — byte-identical to the pre-WORK-027 behavior.
      contextPayload: JSON.stringify(ctx.content, null, 2),
      instructions: ctx.content.instructions,
    };

    this.deps.logger.info('execution.task-built', {
      executionId: input.executionId,
      workItemId: input.workItemId,
      mode: input.mode,
      promptDigest: prompt.digest,
      implementationContextRevision: ctx.revision,
    });

    return {
      task,
      implementationContext: { id: ctx.id, revision: ctx.revision, kind: ctx.kind },
    };
  }
}
