/**
 * WORK-027: ExternalExecutionProvider.
 *
 * Generates a deterministic ExternalExecutionPackage for execution in an
 * external AI platform (ChatGPT / Claude / Z.ai native UI) via the future
 * WorkflowOS Companion browser extension.
 *
 * IMPORTANT SCOPE RULES (WORK-027):
 *   - This provider does NOT execute anything. It produces a handoff-ready
 *     package and returns status 'handoff_ready'.
 *   - It contains NO provider-specific adapters, DOM selectors, or URLs for
 *     Z.ai / ChatGPT / Claude — those belong to WORK-028/029. Provider names
 *     arrive as opaque strings validated against the catalog in the agent
 *     provider registry service.
 *   - The package contains NO secrets (no GitHub/LLM/Vercel tokens, no
 *     webhook secrets). Retrieval is gated by the one-time, short-lived
 *     handoff token mechanism (DefaultExecutionHandoffService).
 *
 * Determinism: the package content (excluding executionId + expiration, which
 * are inherently per-execution) is a pure function of the ExecutionTask. The
 * prompt itself is generated by the ExecutionPromptBuilder from the persisted
 * ImplementationContext (see /work-items — the context authority).
 *
 * This file is private to /agents (PLAT-AC-02).
 */
import type {
  ExecutionProvider,
  ExecutionSubmission,
  ExecutionTask,
  ExternalExecutionPackage,
} from './execution.types.js';

export interface ExternalExecutionProviderOptions {
  /**
   * How long the external handoff window stays open, in milliseconds.
   * Defaults to 1 hour. Configurable so tests can exercise expiry without
   * sleeping.
   */
  readonly packageTtlMs?: number;
  /** Injectable clock for deterministic tests. Defaults to real time. */
  readonly now?: () => Date;
}

export class ExternalExecutionProvider implements ExecutionProvider {
  readonly name = 'external';
  readonly mode = 'external' as const;

  private readonly packageTtlMs: number;
  private readonly now: () => Date;

  constructor(options: ExternalExecutionProviderOptions = {}) {
    this.packageTtlMs = options.packageTtlMs ?? 60 * 60 * 1000;
    this.now = options.now ?? (() => new Date());
  }

  async submit(task: ExecutionTask): Promise<ExecutionSubmission> {
    const expiresAt = new Date(this.now().getTime() + this.packageTtlMs);

    // Deterministic branch suggestion: when the authoritative implementation
    // branch is unknown, suggest the conventional feature branch for the
    // work item label (e.g. WORK-001 → feat/work-001). The external agent
    // MAY use it; WorkflowOS never treats this as authoritative — the branch
    // becomes real only through observed GitHub state.
    const branch =
      task.implementationBranch ?? `feat/${task.workItemLabel.toLowerCase()}`;

    const repositoryOwner = task.repositoryOwner;
    const repositoryName = task.repositoryName;

    const pkg: ExternalExecutionPackage = {
      executionId: task.executionId,
      mode: 'external',
      projectId: task.projectId,
      workItemId: task.workItemId,
      workItemLabel: task.workItemLabel,
      workOrderId: task.workOrderId,
      implementationContextId: task.implementationContextId,
      provider: task.provider,
      model: task.model,
      repository: {
        owner: repositoryOwner,
        name: repositoryName,
        url:
          repositoryOwner && repositoryName
            ? `https://github.com/${repositoryOwner}/${repositoryName}`
            : null,
        defaultBranch: task.repositoryDefaultBranch,
      },
      branch,
      prompt: task.prompt,
      structuredInstructions: [...task.instructions],
      verificationRequirements: [...task.verificationRequirements],
      expectedOutputs: [...task.expectedOutputs],
      browserTestRequirements: [],
      returnCallback: {
        eventsPath: `/execution/${task.executionId}/events`,
        eventTypes: ['started', 'progress', 'completed', 'failed'],
        auth: 'x-callback-token',
        note:
          'POST JSON events to this path with the scoped x-callback-token ' +
          'header issued when the session was prepared (NOT a WorkflowOS API ' +
          'key). The callback token is scoped to THIS execution and to event ' +
          'ingestion only. Events update ONLY the execution record — ' +
          'WorkflowOS observes authoritative GitHub/CI/verification/review ' +
          'state through its own boundaries. External execution can never ' +
          'declare MERGED/VERIFIED/PASS/APPROVED.',
      },
      expiration: expiresAt.toISOString(),
    };

    return {
      executionId: task.executionId,
      provider: task.provider,
      mode: 'external',
      status: 'handoff_ready',
      externalSessionRef: null,
      package: pkg,
      expiresAt,
    };
  }
}
