/**
 * WORK-027: ExternalExecutionProvider.
 *
 * Generates a deterministic ExternalExecutionPackage for execution in an
 * external AI platform (ChatGPT / Claude / Z.ai native UI) via the future
 * WorkflowOS Companion browser extension.
 *
 * IMPORTANT SCOPE RULES (WORK-027):
 *   - This provider does NOT execute anything. It produces a handoff-ready
 *     package and returns status 'handoff_ready'.
 *   - It contains NO provider-specific adapters, DOM selectors, or URLs for
 *     Z.ai / ChatGPT / Claude — those belong to WORK-028/029. Provider names
 *     arrive as opaque strings validated against the catalog in the agent
 *     provider registry service.
 *   - The package contains NO secrets (no GitHub/LLM/Vercel tokens, no
 *     webhook secrets). Retrieval is gated by the one-time, short-lived
 *     handoff token mechanism (DefaultExecutionHandoffService).
 *
 * Determinism: the package content (excluding executionId + expiration +
 * dispatchedAt, which are inherently per-execution/per-dispatch) is a pure
 * function of the ExecutionTask. The prompt itself is generated by the
 * ExecutionPromptBuilder from the persisted ImplementationContext (see
 * /work-items — the context authority).
 *
 * WORK-043 (AR-043-03 — the AUTHORITATIVE dispatch-event timestamp): the
 * package carries `dispatchedAt` — the instant the provider operation body
 * ran (the package derivation IS the external dispatch initiation). The
 * stamped value is the EVENT-TIME anchor for the per-provider sliding-window
 * rate limit: NEVER the execution row's created_at (the reservation) or the
 * handoff log row's created_at (the handoff reservation), both of which can
 * precede the actual dispatch by an arbitrary scheduling gap. The keyed
 * (cross-mode) dispatch path preserves the FIRST dispatch's timestamp
 * structurally: the durable provider-operation ledger stores the settled
 * submission (package + dispatchedAt), and every converged same-key submit
 * REPLAYS that stored submission — the one dispatch event keeps the one
 * timestamp it actually happened at.
 *
 * PR #46 round 9 + round 10 (the GENERATION-FENCED, IDEMPOTENT-SUBMISSION
 * operation boundary): the durable provider-operation ledger (round 8) is
 * real, and the round-9 corrections (the generation-fenced resolution CASes,
 * the immutable key, the resolve-by-identity recovery) are retained in full.
 * The ROUND-10 review found the round-9 protocol's central ordering INVALID:
 *
 *     openOperation()      ← derive a LOCAL identity (no side effects)
 *     attachOperation()    ← durably record it  ← the DB now "knows" H
 *     generate()           ← the operation body  ← may NEVER RUN (crash)
 *
 * The crash window between the durable attach and the body meant a recorded
 * handle proved NOTHING — yet every recovery driver treated it as proof the
 * operation started and resolved by that identity FOREVER, so an operation
 * could remain permanently unexecuted while the ledger proceeded as though
 * it existed. THE DATABASE MUST NEVER INFER THAT AN IRREVERSIBLE PROVIDER
 * OPERATION HAPPENED MERELY BECAUSE WORKFLOWOS PERSISTED AN INTENDED
 * IDENTITY. The round-10 protocol (the review's preferred shape — the
 * provider boundary itself is idempotent):
 *
 *     durable operation key
 *        ↓
 *     startOperation(key, task)   ← the SUBMISSION seam — IDEMPOTENT BY KEY
 *        ↓                           (the contract: a re-call CONVERGES onto
 *        ↓                            the ONE operation, never a second one)
 *     attachOperation(key, gen, H) ← CAS 'pending' → 'started', recorded
 *        ↓                            ONLY AFTER the provider confirmed
 *     resolveOperation(H, task)     ← resolve the CONFIRMED operation by its
 *        ↓                            identity (a status fetch)
 *     complete(key, gen, result)    ← the generation-fenced resolution CAS
 *
 * Every crash point is safe BY THE PROVIDER CONTRACT, not by a ledger
 * inference:
 *   - crash BEFORE the provider accepted the submission → the row is
 *     'pending' (NO handle — the row claims NOTHING); the recovery driver
 *     RE-SUBMITS, which performs the FIRST execution;
 *   - crash AFTER the provider accepted, BEFORE the ledger attach → the row
 *     is STILL 'pending' with NO handle; the recovery driver RE-SUBMITS, and
 *     the idempotent-by-key submission CONVERGES onto the operation the
 *     crash interrupted (the PROVIDER's key→operation mapping is the
 *     authority — never the ledger row);
 *   - crash AFTER the attach ('started') → the provider CONFIRMED the ONE
 *     operation exists; the recovery driver RESOLVES IT BY IDENTITY —
 *     never a re-submission;
 *   - crash AFTER the result, BEFORE the ledger completion → the recovery
 *     resolution replays the SAME provider result.
 *
 * For the current PURE provider, submission derives the identity
 * (`external-package:<key>`) and resolution is re-derivation of the same
 * value from the same task (valid precisely BECAUSE the operation has no
 * side effects — this justification is the provider's own declaration, not
 * an architecture-wide assumption). A future side-effecting provider
 * (WORK-028/029) implements startOperation as a platform submission keyed
 * by the operation key (the platform dedupes — exactly like a platform
 * idempotency key) and resolveOperation as a status fetch on the returned
 * identity.
 *
 * KEY IMMUTABILITY (retained from round 9): COMPLETED and FAILED are BOTH
 * terminal — register NEVER re-arms (it opens a fresh row or returns the
 * existing one); one key identifies ONE logical operation invocation with
 * ONE terminal result; retryability is the driver mechanics' concern (await
 * → take-over → re-submit/resolve-by-identity), never a second operation
 * silently opened under the same key.
 *
 * PR #46 round 11 (the SUBMISSION-ERROR TAXONOMY — the review's blocker:
 * an ambiguous startOperation failure was terminalized as FAILED): a
 * submission error proves NOTHING about whether the provider accepted the
 * operation unless the provider says so. An external request can be
 * accepted remotely and then lose its response (a timeout, a connection
 * reset, process death) — the row was 'pending', the provider operation
 * may EXIST, yet the old catch unconditionally wrote terminal FAILED,
 * closing the key forever while every later same-key submission replayed a
 * failure the provider never reported (the provider's idempotency-by-key
 * guarantee could never again be used to converge — WorkflowOS itself
 * closed the key). The taxonomy:
 *
 *   - DEFINITIVE REJECT — the typed ProviderOperationRejectedError: the
 *     provider PROVABLY refused the operation and guarantees NO operation
 *     exists for the key (no side effect can ever occur). The ONLY
 *     submission error that may terminally fail the key, through the
 *     ledger's definitive-reject transition ('pending' @ the driver's
 *     generation → 'failed');
 *   - ACCEPTANCE UNKNOWN — every other submission error: the row REMAINS
 *     'pending' (recoverable — the provider's key→operation mapping is the
 *     authority), the keyed submit fails closed with the typed
 *     submission-outcome-unknown error, and the SAME-KEY RETRY re-submits
 *     and CONVERGES through the provider's idempotency-by-key dedup,
 *     attaches the returned identity, and resolves the ONE operation.
 *
 * THE DATABASE NEVER CLOSES A KEY ON AN AMBIGUOUS SUBMISSION ERROR.
 *
 * UNKEYED tasks (the mainline one-shot dispatch — the
 * DefaultExecutionService path) keep the exact pre-WORK-042 behavior: a
 * direct generation with NO ledger (each mainline execution dispatches
 * exactly once through its own record lifecycle).
 *
 * This file is private to /agents (PLAT-AC-02).
 */
import type { Logger } from '@platform/logger.js';
import { ProviderOperationRejectedError } from './execution.types.js';
import type {
  ExecutionProvider,
  ExecutionSubmission,
  ExecutionTask,
  ExternalExecutionPackage,
} from './execution.types.js';
import type {
  ExecutionProviderOperationStore,
  ProviderOperationRecord,
} from './pg-execution-provider-operation-repository.js';

export interface ExternalExecutionProviderOptions {
  /**
   * How long the external handoff window stays open, in milliseconds.
   * Defaults to 1 hour. Configurable so tests can exercise expiry without
   * sleeping.
   */
  readonly packageTtlMs?: number;
  /** Injectable clock for deterministic tests. Defaults to real time. */
  readonly now?: () => Date;
  /**
   * PR #46 round 8: the DURABLE PROVIDER-OPERATION LEDGER store. REQUIRED
   * for keyed dispatches (the cross-mode handoff dispatch) — a keyed submit
   * without a store is a wiring error and fails loudly. Unkeyed (mainline)
   * submissions never touch the store.
   */
  readonly operationStore?: ExecutionProviderOperationStore;
  /**
   * How long a same-key submit awaits a PENDING ledger row's resolution
   * before TAKING OVER the drive (the process-loss recovery window).
   * Defaults to 5s. Correctness never depends on this knob (the
   * generation-fenced resolution CAS arbitrates drivers; the loser converges
   * to the winner) — it only trades await time against duplicate recovery
   * work after a crashed driver.
   */
  readonly operationResolutionWindowMs?: number;
  /** The ledger poll interval while awaiting a pending resolution. */
  readonly operationPollIntervalMs?: number;
  /** Optional structured logger (convergence/take-over observability). */
  readonly logger?: Logger;
}

/** Sentinel: the ledger row is PENDING — the operation is in flight. */
const IN_FLIGHT = Symbol('in-flight');
/**
 * Sentinel: the drive must YIELD to another driver (this driver's generation
 * is stale, or a concurrent driver recorded the identity / is resolving the
 * row) — the caller re-enters the converge/await/take-over loop.
 */
const RECOVERY_CONTINUE = Symbol('recovery-continue');
/** Type alias for the two drive outcomes that are not a submission. */
type DriveOutcome = ExecutionSubmission | typeof RECOVERY_CONTINUE;

/**
 * The maximum converge → await → take-over → drive cycles one keyed submit
 * will run before failing loudly (a pathological-contention guard — every
 * cycle costs a full resolution window, so this bound never fires in
 * practice; it exists so a permanently contended row surfaces as an error
 * instead of looping forever).
 */
const MAX_RECOVERY_CYCLES = 8;

export class ExternalExecutionProvider implements ExecutionProvider {
  readonly name = 'external';
  readonly mode = 'external' as const;

  private readonly packageTtlMs: number;
  private readonly now: () => Date;
  private readonly operationStore?: ExecutionProviderOperationStore;
  private readonly resolutionWindowMs: number;
  private readonly pollIntervalMs: number;
  private readonly logger?: Logger;

  constructor(options: ExternalExecutionProviderOptions = {}) {
    this.packageTtlMs = options.packageTtlMs ?? 60 * 60 * 1000;
    this.now = options.now ?? (() => new Date());
    this.operationStore = options.operationStore;
    this.resolutionWindowMs = options.operationResolutionWindowMs ?? 5_000;
    this.pollIntervalMs = options.operationPollIntervalMs ?? 25;
    this.logger = options.logger;
  }

  async submit(task: ExecutionTask): Promise<ExecutionSubmission> {
    const key = task.dispatchIdempotencyKey;
    if (!key) {
      // UNKEYED (the mainline one-shot dispatch): the pre-WORK-042 behavior
      // — a direct generation, no registry, no ledger row.
      return this.generate(task);
    }
    // KEYED (the cross-mode handoff dispatch): resolve through the DURABLE
    // provider-operation ledger — the row for this key IS the operation.
    const store = this.operationStore;
    if (!store) {
      throw new Error(
        `external-execution-operation-store-required: execution ${task.executionId} was submitted with dispatch idempotency key ${key}, but no durable provider-operation ledger store is wired (PR #46 round 8 — the keyed registry MUST be durable)`,
      );
    }
    const { opened } = await store.register({
      idempotencyKey: key,
      provider: task.provider,
      executionId: task.executionId,
      mode: 'external',
    });
    // The recovery loop: the original drive (generation 1) and every later
    // converged submit share ONE protocol — converge (terminal → replay /
    // stored failure), await the active driver's durable resolution, and
    // after the resolution window (process loss) TAKE OVER the drive of the
    // SAME row with a NEW GENERATION TOKEN.
    let drive: DriveOutcome | undefined = opened
      ? await this.attemptDrive(store, key, task, 1)
      : undefined;
    for (let cycle = 0; ; cycle++) {
      if (drive !== undefined && drive !== RECOVERY_CONTINUE) {
        return drive;
      }
      if (cycle >= MAX_RECOVERY_CYCLES) {
        throw new Error(
          `external-execution-recovery-exhausted: the provider operation ${key} for execution ${task.executionId} did not converge within ${MAX_RECOVERY_CYCLES} recovery cycles (pathological contention — the row remains the single durable operation; retry the dispatch)`,
        );
      }
      // Converge through the row: COMPLETED → replay; FAILED → the stored
      // terminal failure; PENDING → await the active driver.
      const row = await store.get(key);
      const converged = this.convergeFrom(row, key);
      if (converged !== IN_FLIGHT) {
        return converged;
      }
      const resolved = await this.awaitResolution(store, key);
      if (resolved) {
        return this.convergeFrom(resolved, key) as ExecutionSubmission;
      }
      // The window elapsed — the presumed-dead driver. The take-over CAS
      // records the recovery drive on the SAME row (generation + 1) and
      // RETURNS THE NEW GENERATION TOKEN (the fencing token this driver must
      // present to complete/fail — every previous generation becomes
      // structurally incapable of resolving the operation).
      const takeover = await store.takeOver(key);
      if (!takeover.tookOver) {
        continue; // the row resolved in the interim — converge next cycle
      }
      this.logger?.info('execution.external.provider-operation-takeover', {
        idempotencyKey: key,
        executionId: task.executionId,
        generation: takeover.generation,
        resolutionWindowMs: this.resolutionWindowMs,
      });
      drive = await this.attemptDrive(store, key, task, takeover.generation!);
    }
  }

  /**
   * DRIVE the ONE ledger operation for the key as the ACTIVE driver of
   * `generation`. The protocol (round 10 — the SUBMIT-THEN-ATTACH ordering;
   * round 11 — the submission-error taxonomy):
   *
   *   - The row resolved → converge (replay / the stored failure).
   *   - The row's generation moved on → this driver is STALE: yield (the
   *     caller converges onto the active driver's outcome; a stale driver
   *     never resolves the row).
   *   - The row is 'started' (the provider CONFIRMED the ONE operation — the
   *     handle was attached AFTER the confirmation): RESOLVE BY IDENTITY —
   *     {@link resolveOperation} — NEVER a re-submission.
   *   - The row is 'pending' (the submission is NOT durably confirmed — the
   *     row makes NO claim about the provider): SUBMIT through the
   *     IDEMPOTENT-BY-KEY {@link startOperation} seam (safe whether or not a
   *     previous attempt started the operation — the provider's
   *     key→operation mapping is the authority), durably ATTACH the returned
   *     identity (the CAS: 'pending' → 'started' @ THIS generation), then
   *     resolve the CONFIRMED operation by its identity.
   *
   * A submission FAILURE (round 11) is classified by WHAT THE ERROR PROVES:
   * the typed ProviderOperationRejectedError is a DEFINITIVE REJECT (the
   * provider guarantees no operation exists — terminal FAILED allowed);
   * every other submission error is ACCEPTANCE-UNKNOWN (the provider may
   * have accepted the operation and lost the response) — the row REMAINS
   * 'pending' and recoverable, and the keyed submit fails closed with the
   * typed outcome-unknown error (never a terminal FAILED: the same-key
   * retry converges through the provider's idempotency-by-key dedup).
   */
  private async attemptDrive(
    store: ExecutionProviderOperationStore,
    key: string,
    task: ExecutionTask,
    generation: number,
  ): Promise<DriveOutcome> {
    const row = await store.get(key);
    if (!row) {
      // Unreachable in practice (register/takeOver created the row); yield
      // defensively so the caller re-resolves.
      return RECOVERY_CONTINUE;
    }
    if (row.state === 'completed' || row.state === 'failed') {
      // A terminal row always converges (replay or the stored failure) — it
      // can never yield the in-flight marker.
      return this.convergeFrom(row, key) as ExecutionSubmission;
    }
    if (row.generation !== generation) {
      // A newer generation owns the drive — this driver is stale. It must
      // NOT resolve the row (the generation-fenced CAS would reject it
      // anyway); it converges onto the active driver's outcome instead.
      return RECOVERY_CONTINUE;
    }
    if (row.state === 'started' && row.providerOperationHandle != null) {
      // The provider CONFIRMED the ONE operation (the handle was attached
      // AFTER startOperation returned it): resolve the CONFIRMED operation
      // by its identity. NEVER a re-submission.
      return this.resolveByIdentity(
        store,
        key,
        task,
        generation,
        row.providerOperationHandle,
      );
    }
    // The row is 'pending' — the submission is NOT durably confirmed (the
    // row makes NO claim about the provider). SUBMIT through the
    // IDEMPOTENT-BY-KEY seam: safe whether or not a previous attempt
    // started the operation (a re-submission CONVERGES onto the ONE
    // operation — the provider's key→operation mapping is the authority,
    // never the ledger row).
    let handle: string;
    try {
      handle = await this.startOperation(key, task);
    } catch (err) {
      if (err instanceof ProviderOperationRejectedError) {
        // DEFINITIVE REJECT (PR #46 round 11 — the submission-error
        // taxonomy): the provider PROVABLY REFUSED the operation and
        // guarantees NO operation exists for the key (no side effect can
        // ever occur). This is the ONLY submission error that may
        // terminally fail the key — the pending row's single terminal-
        // failure path is the ledger's definitive-reject transition.
        return this.failDrive(
          store, key, task, generation, err, 'definitive-reject',
        );
      }
      // ACCEPTANCE UNKNOWN (PR #46 round 11 — the review's blocker): a
      // transport failure (a timeout, a connection reset, a LOST RESPONSE,
      // process death...) proves NOTHING about whether the provider
      // accepted the operation — the provider may have accepted it, and the
      // operation may exist and succeed remotely. The row REMAINS 'pending'
      // (the row claims nothing; the provider's key→operation mapping is
      // the authority): the key stays RECOVERABLE — the same-key retry
      // re-submits and CONVERGES through the provider's idempotency-by-key
      // dedup, attaches the returned identity, and resolves the ONE
      // operation. NEVER a terminal FAILED from an ambiguous error: that
      // would close the key while the provider operation may exist and
      // succeed — every later same-key submission would replay a failure
      // the provider never reported, and the provider's idempotency-by-key
      // guarantee could never again be used to converge because WorkflowOS
      // itself closed the key.
      this.logger?.warn(
        'execution.external.provider-operation-submission-outcome-unknown',
        {
          idempotencyKey: key,
          executionId: task.executionId,
          generation,
          error: (err as Error).message,
        },
      );
      throw new Error(
        `external-execution-submission-outcome-unknown: the submission for provider operation ${key} (execution ${task.executionId}) failed ambiguously (${(err as Error).message}) — the provider may have accepted the operation; the ledger row stays pending and the same-key retry converges through the provider's idempotency-by-key dedup`,
      );
    }
    const attached = await store.attachOperation(key, generation, handle);
    if (!attached) {
      // The CAS lost: a concurrent driver attached the identity first, the
      // generation moved on, or the row resolved. Re-read: if the identity
      // is now recorded at OUR generation, resolve by it; otherwise yield.
      const fresh = await store.get(key);
      if (
        fresh &&
        fresh.state === 'started' &&
        fresh.generation === generation &&
        fresh.providerOperationHandle != null
      ) {
        return this.resolveByIdentity(
          store,
          key,
          task,
          generation,
          fresh.providerOperationHandle,
        );
      }
      return RECOVERY_CONTINUE;
    }
    // The provider CONFIRMED the operation + the row records it ('started'):
    // resolve the CONFIRMED operation by its identity (a status fetch for a
    // platform provider; re-derivation for the pure default provider).
    return this.resolveByIdentity(store, key, task, generation, handle);
  }

  /**
   * RESOLVE the CONFIRMED operation by its durable identity (the recovery
   * path for a 'started' row that already records its provider operation
   * handle): the provider returns the ONE operation's outcome through the
   * contract-bound {@link resolveOperation} seam — the operation is NEVER
   * re-submitted here. The resolution commits through the same
   * generation-fenced CAS as a submission drive.
   */
  private async resolveByIdentity(
    store: ExecutionProviderOperationStore,
    key: string,
    task: ExecutionTask,
    generation: number,
    handle: string,
  ): Promise<DriveOutcome> {
    this.logger?.info(
      'execution.external.provider-operation-resolve-by-identity',
      { idempotencyKey: key, executionId: task.executionId, generation, handle },
    );
    try {
      const submission = await this.resolveOperation(handle, task);
      return await this.settle(store, key, task, generation, submission);
    } catch (err) {
      return this.failDrive(
        store, key, task, generation, err, 'resolution-failure',
      );
    }
  }

  /**
   * SETTLE a resolved submission through the GENERATION-FENCED resolution
   * CAS: the ACTIVE driver's generation stores the ONE terminal result; a
   * CAS loss means the driver is stale or lost the race — it converges to
   * the winner's recorded outcome (a still-pending row at a NEWER generation
   * means the active recovery driver owns the resolution — this driver
   * yields and awaits it; it NEVER returns its own lookalike result).
   */
  private async settle(
    store: ExecutionProviderOperationStore,
    key: string,
    task: ExecutionTask,
    generation: number,
    submission: ExecutionSubmission,
  ): Promise<DriveOutcome> {
    const { completed, current } = await store.complete(
      key,
      generation,
      submission,
    );
    if (completed) {
      return submission;
    }
    if (current && current.state === 'completed' && current.submission) {
      this.logger?.info(
        'execution.external.provider-operation-converged-late-driver',
        { idempotencyKey: key, executionId: task.executionId },
      );
      return current.submission;
    }
    if (current && current.state === 'failed') {
      throw new Error(
        current.errorMessage ??
          `external-execution-operation-failed: the provider operation ${key} already resolved as failed`,
      );
    }
    // Still pending at a NEWER generation: the active recovery driver owns
    // the resolution — yield and converge onto its outcome.
    return RECOVERY_CONTINUE;
  }

  /**
   * Record a failed drive through the GENERATION-FENCED failure CAS. The
   * `outcome` discriminator names WHICH failure transition this is (PR #46
   * round 11 — the submission-error taxonomy):
   *
   *   - 'definitive-reject' — the provider PROVABLY refused the submission
   *     (the typed ProviderOperationRejectedError; the row is 'pending'):
   *     the ledger's DEFINITIVE-REJECT transition is the ONLY way an
   *     unconfirmed submission may terminally fail the key;
   *   - 'resolution-failure' — a CONFIRMED operation's resolution failed
   *     (the row is 'started').
   *
   * If the CAS wins, the failure is the operation's terminal outcome. If it
   * loses, this driver's generation is STALE (superseded by a take-over): its
   * failure is structurally DISCARDED — it can never defeat the active
   * recovery generation — and the driver converges to the row's recorded or
   * eventual outcome instead (a COMPLETED row still resolves the same key;
   * a still-pending row is the active driver's to resolve).
   */
  private async failDrive(
    store: ExecutionProviderOperationStore,
    key: string,
    task: ExecutionTask,
    generation: number,
    err: unknown,
    outcome: 'definitive-reject' | 'resolution-failure',
  ): Promise<DriveOutcome> {
    const message = (err as Error).message;
    if (outcome === 'definitive-reject') {
      // The DEFINITIVE-REJECT CAS ('pending' @ THIS generation → 'failed'):
      // legal ONLY because the provider PROVED no operation exists for the
      // key — an AMBIGUOUS submission error NEVER reaches this transition
      // (the row stays 'pending' and recoverable instead).
      await store.reject(key, generation, message);
    } else {
      // The resolution-failure CAS ('started' @ THIS generation →
      // 'failed') — the confirmed operation's resolution failure.
      await store.fail(key, generation, message);
    }
    const row = await store.get(key);
    if (row && row.state === 'completed' && row.submission) {
      this.logger?.info(
        'execution.external.provider-operation-converged-after-failure',
        { idempotencyKey: key, executionId: task.executionId },
      );
      return row.submission;
    }
    if (row && row.state === 'failed') {
      throw new Error(
        row.errorMessage ??
          `external-execution-operation-failed: the provider operation ${key} resolved as failed`,
      );
    }
    // Still pending at a NEWER generation: this stale driver's failure was
    // DISCARDED (0 rows — the generation fence); the active recovery driver
    // owns the resolution. Yield and converge onto its outcome.
    return RECOVERY_CONTINUE;
  }

  /**
   * Map a ledger row to the converged submit outcome: COMPLETED → REPLAY the
   * stored submission; FAILED → surface the stored terminal failure (round 9:
   * the key is immutable — a terminally failed operation is a KNOWN outcome,
   * never re-armed by a later same-key submit); PENDING or STARTED (either
   * non-terminal state) → the in-flight marker (await/take over).
   */
  private convergeFrom(
    record: ProviderOperationRecord | null,
    key: string,
  ): ExecutionSubmission | typeof IN_FLIGHT {
    if (!record) {
      // Unreachable in practice (register returned opened:false → the row
      // exists); treat defensively as in-flight so the caller re-resolves.
      return IN_FLIGHT;
    }
    if (record.state === 'completed') {
      if (!record.submission) {
        throw new Error(
          `external-execution-operation-result-missing: the completed provider operation ${key} has no stored submission (ledger corruption)`,
        );
      }
      this.logger?.info(
        'execution.external.provider-operation-replayed',
        { idempotencyKey: key, executionId: record.executionId },
      );
      return record.submission;
    }
    if (record.state === 'failed') {
      throw new Error(
        record.errorMessage ??
          `external-execution-operation-failed: the provider operation ${key} resolved as failed`,
      );
    }
    // 'pending' (submission unconfirmed — re-submit on the recovery drive)
    // or 'started' (confirmed — resolve by identity): both are IN FLIGHT
    // from a converged submit's perspective (await the active driver).
    return IN_FLIGHT;
  }

  /**
   * Await a NON-TERMINAL ledger row's durable resolution, polling the ledger
   * until the row reaches a TERMINAL state (COMPLETED/FAILED — returns the
   * row) or the resolution window elapses (returns null — the presumed-dead
   * driver; the caller takes over the drive of the SAME row). PR #46 round
   * 10: 'pending' and 'started' are BOTH non-terminal in-flight states (the
   * active driver owns the submission or the resolution of the SAME row).
   */
  private async awaitResolution(
    store: ExecutionProviderOperationStore,
    key: string,
  ): Promise<ProviderOperationRecord | null> {
    const deadline = Date.now() + this.resolutionWindowMs;
    for (;;) {
      await new Promise((resolve) => setTimeout(resolve, this.pollIntervalMs));
      const row = await store.get(key);
      if (row && (row.state === 'completed' || row.state === 'failed')) {
        return row;
      }
      if (Date.now() >= deadline) {
        return null;
      }
    }
  }

  /**
   * PR #46 round 10 (the IDEMPOTENT PROVIDER-SUBMISSION seam) + round 11
   * (the SUBMISSION-ERROR TAXONOMY): SUBMIT the ONE provider operation for
   * the key — the operation's entry into the provider's own operation
   * space. THE CONTRACT — startOperation(key) MUST
   * BE IDEMPOTENT BY KEY: invoking it again for a key that already owns a
   * provider operation MUST CONVERGE onto that ONE operation (returning its
   * identity), NEVER start a second one — exactly like a platform idempotency
   * key. This is the provider-boundary guarantee that makes EVERY crash
   * point safe (the round-10 correction — the review's preferred shape):
   *   - crash BEFORE the provider accepted → a re-submission performs the
   *     FIRST execution;
   *   - crash AFTER the provider accepted, BEFORE the ledger attach → a
   *     re-submission CONVERGES onto the operation the crash interrupted
   *     (the PROVIDER's key→operation mapping is the authority, never the
   *     ledger row — the database never infers a start from a persisted
   *     intended identity).
   *
   * THE ERROR CONTRACT (round 11 — DEFINITIVE REJECT vs ACCEPTANCE UNKNOWN):
   * throw the typed {@link ProviderOperationRejectedError} ONLY when the
   * provider PROVABLY refused the operation (it guarantees NO operation
   * exists for the key — no side effect can ever occur; terminal FAILED is
   * allowed). EVERY other thrown error is treated as ACCEPTANCE-UNKNOWN
   * (a timeout, a connection reset, a lost response — the provider may have
   * accepted the operation): the ledger row stays 'pending' and recoverable,
   * and the same-key retry converges through the idempotency-by-key dedup
   * above. NEVER throw the typed reject for an ambiguous failure — the key
   * would close while the provider operation may exist and succeed.
   *
   * The DEFAULT provider's submission is a PURE derivation (no side
   * effects), so re-submission trivially converges; the durable identity of
   * the (pure) operation is derived from the key. A platform-backed provider
   * (WORK-028/029) submits the operation to the platform keyed by the
   * operation key (the platform dedupes) and returns the platform's durable
   * operation identity. Protected so tests can instrument/park the
   * submission crash points (before/after the provider accepted) and
   * simulate ambiguous acceptances + definitive rejects.
   */
  protected async startOperation(
    idempotencyKey: string,
    _task: ExecutionTask,
  ): Promise<string> {
    return `external-package:${idempotencyKey}`;
  }

  /**
   * PR #46 round 9 + round 10 (the resolve-by-identity seam): resolve the
   * CONFIRMED operation by its durable identity and return the ONE
   * operation's outcome. Reachable ONLY for a 'started' row (the provider
   * CONFIRMED the operation — startOperation returned this identity at some
   * generation). MUST NEVER start a SECOND provider operation: a
   * platform-backed provider (WORK-028/029) performs a status fetch on the
   * identity. The DEFAULT provider's operations are PURE (deterministic
   * package construction): resolution is RE-DERIVATION of the same value from the same task — valid precisely because the operation has no side
   * effects. This is the provider-side same-key convergence guarantee that
   * makes the take-over recovery sound WITHOUT assuming provider determinism
   * architecture-wide. Protected so tests can instrument/park the
   * recovery-resolution point.
   */
  protected async resolveOperation(
    providerOperationHandle: string,
    task: ExecutionTask,
  ): Promise<ExecutionSubmission> {
    void providerOperationHandle; // the default identity is the key itself —
    // pure re-derivation does not need the handle (platform providers do).
    return this.derive(task);
  }

  /**
   * Generate the package submission for an UNKEYED (mainline one-shot)
   * dispatch — the pre-WORK-042 behavior. PR #46 round 10: the KEYED path
   * NEVER calls this seam (the keyed operation lives behind the
   * startOperation submission + resolveOperation resolution contract);
   * keyed tests assert ZERO generate entries as a structural proof that the
   * keyed dispatch never runs the raw one-shot body. Protected so tests can
   * instrument the unkeyed path.
   */
  protected async generate(task: ExecutionTask): Promise<ExecutionSubmission> {
    return this.derive(task);
  }

  /** The pure package derivation shared by the drive + the resolution seams. */
  private async derive(task: ExecutionTask): Promise<ExecutionSubmission> {
    const now = this.now();
    const expiresAt = new Date(now.getTime() + this.packageTtlMs);
    // AR-043-03: the AUTHORITATIVE DISPATCH-EVENT timestamp — stamped at the
    // moment the provider operation body runs (the package derivation IS the
    // external dispatch initiation). This instant — NOT the execution row's
    // or the handoff log row's creation (both are reservations that can
    // precede the actual dispatch by an arbitrary scheduling gap) — anchors
    // the per-provider sliding-window rate limit. The keyed dispatch path
    // preserves the FIRST dispatch's value: the settled submission (this
    // package) is stored in the durable provider-operation ledger and every
    // converged same-key submit replays it verbatim.
    const dispatchedAt = now.toISOString();

    // Deterministic branch suggestion: when the authoritative implementation
    // branch is unknown, suggest the conventional feature branch for the
    // work item label (e.g. WORK-001 → feat/work-001). The external agent
    // MAY use it; WorkflowOS never treats this as authoritative — the branch
    // becomes real only through observed GitHub state.
    const branch =
      task.implementationBranch ?? `feat/${task.workItemLabel.toLowerCase()}`;

    const repositoryOwner = task.repositoryOwner;
    const repositoryName = task.repositoryName;

    const pkg: ExternalExecutionPackage = {
      executionId: task.executionId,
      mode: 'external',
      projectId: task.projectId,
      workItemId: task.workItemId,
      workItemLabel: task.workItemLabel,
      workOrderId: task.workOrderId,
      implementationContextId: task.implementationContextId,
      provider: task.provider,
      model: task.model,
      repository: {
        owner: repositoryOwner,
        name: repositoryName,
        url:
          repositoryOwner && repositoryName
            ? `https://github.com/${repositoryOwner}/${repositoryName}`
            : null,
        defaultBranch: task.repositoryDefaultBranch,
      },
      branch,
      prompt: task.prompt,
      structuredInstructions: [...task.instructions],
      verificationRequirements: [...task.verificationRequirements],
      expectedOutputs: [...task.expectedOutputs],
      browserTestRequirements: [],
      returnCallback: {
        eventsPath: `/execution/${task.executionId}/events`,
        eventTypes: ['started', 'progress', 'completed', 'failed'],
        auth: 'x-callback-token',
        note:
          'POST JSON events to this path with the scoped x-callback-token ' +
          'header issued when the session was prepared (NOT a WorkflowOS API ' +
          'key). The callback token is scoped to THIS execution and to event ' +
          'ingestion only. Events update ONLY the execution record — ' +
          'WorkflowOS observes authoritative GitHub/CI/verification/review ' +
          'state through its own boundaries. External execution can never ' +
          'declare MERGED/VERIFIED/PASS/APPROVED.',
      },
      expiration: expiresAt.toISOString(),
      dispatchedAt,
    };

    return {
      executionId: task.executionId,
      provider: task.provider,
      mode: 'external',
      status: 'handoff_ready',
      externalSessionRef: null,
      package: pkg,
      expiresAt,
    };
  }
}
