/**
 * WORK-027: ExternalExecutionProvider.
 *
 * Generates a deterministic ExternalExecutionPackage for execution in an
 * external AI platform (ChatGPT / Claude / Z.ai native UI) via the future
 * WorkflowOS Companion browser extension.
 *
 * IMPORTANT SCOPE RULES (WORK-027):
 *   - This provider does NOT execute anything. It produces a handoff-ready
 *     package and returns status 'handoff_ready'.
 *   - It contains NO provider-specific adapters, DOM selectors, or URLs for
 *     Z.ai / ChatGPT / Claude — those belong to WORK-028/029. Provider names
 *     arrive as opaque strings validated against the catalog in the agent
 *     provider registry service.
 *   - The package contains NO secrets (no GitHub/LLM/Vercel tokens, no
 *     webhook secrets). Retrieval is gated by the one-time, short-lived
 *     handoff token mechanism (DefaultExecutionHandoffService).
 *
 * Determinism: the package content (excluding executionId + expiration, which
 * are inherently per-execution) is a pure function of the ExecutionTask. The
 * prompt itself is generated by the ExecutionPromptBuilder from the persisted
 * ImplementationContext (see /work-items — the context authority).
 *
 * PR #46 round 7 (the provider-operation exactly-once boundary — the
 * architect's contract option 1): `submit` is IDEMPOTENT BY DISPATCH KEY.
 * When the task carries a `dispatchIdempotencyKey` (the cross-mode handoff
 * dispatch ALWAYS does — the WORK-042 service derives it from the handoff
 * identity), a same-key submit returns the REGISTERED operation — the stored
 * `ExecutionSubmission` of the FIRST generation for that key — NEVER a
 * second operation. A reclaiming owner whose re-dispatch converges here
 * observes the ORIGINAL operation's package + expiry (byte-identical to what
 * the original owner's in-flight submit will return), so two actors can never
 * produce two independent provider operations for one logical handoff.
 * CONVERGENCE DOES NOT DEPEND ON DETERMINISM: the registry returns the stored
 * first-generation submission object, not a re-computed lookalike — a future
 * non-deterministic provider (WORK-028/029) satisfies the same contract by
 * forwarding the key to the platform's idempotency mechanism.
 *
 * This file is private to /agents (PLAT-AC-02).
 */
import type {
  ExecutionProvider,
  ExecutionSubmission,
  ExecutionTask,
  ExternalExecutionPackage,
} from './execution.types.js';

export interface ExternalExecutionProviderOptions {
  /**
   * How long the external handoff window stays open, in milliseconds.
   * Defaults to 1 hour. Configurable so tests can exercise expiry without
   * sleeping.
   */
  readonly packageTtlMs?: number;
  /** Injectable clock for deterministic tests. Defaults to real time. */
  readonly now?: () => Date;
}

export class ExternalExecutionProvider implements ExecutionProvider {
  readonly name = 'external';
  readonly mode = 'external' as const;

  private readonly packageTtlMs: number;
  private readonly now: () => Date;
  /**
   * PR #46 round 7: the keyed operation registry — the durable-by-key record
   * of the provider operations THIS provider instance started. Key = the
   * task's `dispatchIdempotencyKey` (the cross-mode handoff dispatch) or the
   * executionId (the mainline one-shot dispatch — each mainline execution
   * dispatches exactly once, so the fallback key is never reused). A
   * same-key submit CONVERGES to the registered operation.
   */
  private readonly operations = new Map<string, Promise<ExecutionSubmission>>();

  constructor(options: ExternalExecutionProviderOptions = {}) {
    this.packageTtlMs = options.packageTtlMs ?? 60 * 60 * 1000;
    this.now = options.now ?? (() => new Date());
  }

  async submit(task: ExecutionTask): Promise<ExecutionSubmission> {
    const key = task.dispatchIdempotencyKey ?? task.executionId;
    const registered = this.operations.get(key);
    if (registered) {
      // PR #46 round 7 — CONVERGE: a same-key submit (a retried or reclaimed
      // dispatch — e.g. a reclaiming owner's re-dispatch racing the original
      // owner's still-in-flight submit) returns the REGISTERED operation's
      // submission — the SAME provider operation (awaited when still in
      // flight), NOT a second generation. The convergence holds even if a
      // later task differed (it returns the FIRST operation's result, not a
      // re-computed one) — the contract does not depend on determinism.
      return registered;
    }
    // Start the ONE provider operation for this key. The generation itself is
    // the operation; registering its promise before awaiting makes every
    // subsequent same-key submit converge onto THIS operation.
    const operation = this.generate(task);
    this.operations.set(key, operation);
    return operation;
  }

  /** Generate the package submission (the provider operation body). */
  private async generate(task: ExecutionTask): Promise<ExecutionSubmission> {
    const expiresAt = new Date(this.now().getTime() + this.packageTtlMs);

    // Deterministic branch suggestion: when the authoritative implementation
    // branch is unknown, suggest the conventional feature branch for the
    // work item label (e.g. WORK-001 → feat/work-001). The external agent
    // MAY use it; WorkflowOS never treats this as authoritative — the branch
    // becomes real only through observed GitHub state.
    const branch =
      task.implementationBranch ?? `feat/${task.workItemLabel.toLowerCase()}`;

    const repositoryOwner = task.repositoryOwner;
    const repositoryName = task.repositoryName;

    const pkg: ExternalExecutionPackage = {
      executionId: task.executionId,
      mode: 'external',
      projectId: task.projectId,
      workItemId: task.workItemId,
      workItemLabel: task.workItemLabel,
      workOrderId: task.workOrderId,
      implementationContextId: task.implementationContextId,
      provider: task.provider,
      model: task.model,
      repository: {
        owner: repositoryOwner,
        name: repositoryName,
        url:
          repositoryOwner && repositoryName
            ? `https://github.com/${repositoryOwner}/${repositoryName}`
            : null,
        defaultBranch: task.repositoryDefaultBranch,
      },
      branch,
      prompt: task.prompt,
      structuredInstructions: [...task.instructions],
      verificationRequirements: [...task.verificationRequirements],
      expectedOutputs: [...task.expectedOutputs],
      browserTestRequirements: [],
      returnCallback: {
        eventsPath: `/execution/${task.executionId}/events`,
        eventTypes: ['started', 'progress', 'completed', 'failed'],
        auth: 'x-callback-token',
        note:
          'POST JSON events to this path with the scoped x-callback-token ' +
          'header issued when the session was prepared (NOT a WorkflowOS API ' +
          'key). The callback token is scoped to THIS execution and to event ' +
          'ingestion only. Events update ONLY the execution record — ' +
          'WorkflowOS observes authoritative GitHub/CI/verification/review ' +
          'state through its own boundaries. External execution can never ' +
          'declare MERGED/VERIFIED/PASS/APPROVED.',
      },
      expiration: expiresAt.toISOString(),
    };

    return {
      executionId: task.executionId,
      provider: task.provider,
      mode: 'external',
      status: 'handoff_ready',
      externalSessionRef: null,
      package: pkg,
      expiresAt,
    };
  }
}
