import { randomUUID } from 'node:crypto';
import type { DatabaseClient } from '../postgres/database-client.js';

/**
 * Durable PostgreSQL reference to a large/immutable object stored in object
 * storage (DATA3-AC-01 / DATA3-AC-02).
 *
 * The relational record holds enough provenance (storage key, provider,
 * content length, content type, digest, free-form metadata) to locate and
 * validate the stored object WITHOUT embedding its full body in a core
 * relational record.
 *
 * This is an *infrastructure-level* record. Domain modules that need to
 * associate large artifacts (e.g. agent transcripts, PR snapshots, generated
 * reports, CI artifacts) will add domain tables that reference
 * `wfos_artifact_metadata.id` — they do not duplicate this contract.
 */
export interface ArtifactMetadata {
  /** UUID primary key (generated by PostgreSQL). */
  readonly id: string;
  /** Provider-independent storage reference used by {@link ObjectStore}. */
  readonly storageKey: string;
  /** Name of the storage provider that holds the object (e.g. `fs`, `s3`). */
  readonly storageProvider: string;
  /** Object size in bytes. */
  readonly contentLength: number;
  /** MIME/content type if known. */
  readonly contentType: string | null;
  /** SHA-256 digest of the object content if known. */
  readonly digestSha256: string | null;
  /** Free-form provenance metadata. */
  readonly metadata: Record<string, unknown>;
  readonly createdAt: Date;
}

export interface CreateArtifactMetadataInput {
  storageKey: string;
  storageProvider: string;
  contentLength: number;
  contentType?: string | null;
  digestSha256?: string | null;
  metadata?: Record<string, unknown>;
}

/**
 * Repository for the `wfos_artifact_metadata` table (DATA3-AC-01 / DATA3-AC-02).
 *
 * This is the canonical way domain code persists durable references to
 * large/immutable artifacts. The repository hides SQL behind a stable
 * interface so future schema changes do not ripple into domain modules.
 *
 * The repository depends on {@link DatabaseClient}, never on `pg` or `pglite`
 * directly.
 */
export class ArtifactMetadataRepository {
  constructor(private readonly db: DatabaseClient) {}

  async create(input: CreateArtifactMetadataInput): Promise<ArtifactMetadata> {
    const id = randomUUID();
    const result = await this.db.query<{
      id: string;
      storage_key: string;
      storage_provider: string;
      content_length: string;
      content_type: string | null;
      digest_sha256: string | null;
      metadata: Record<string, unknown>;
      created_at: Date;
    }>(
      `INSERT INTO wfos_artifact_metadata
         (id, storage_key, storage_provider, content_length, content_type, digest_sha256, metadata)
       VALUES ($1, $2, $3, $4, $5, $6, $7)
       RETURNING id, storage_key, storage_provider, content_length, content_type,
                 digest_sha256, metadata, created_at`,
      [
        id,
        input.storageKey,
        input.storageProvider,
        input.contentLength,
        input.contentType ?? null,
        input.digestSha256 ?? null,
        JSON.stringify(input.metadata ?? {}),
      ],
    );
    const row = result.rows[0]!;
    return this.mapRow(row);
  }

  async findById(id: string): Promise<ArtifactMetadata | null> {
    const result = await this.db.query<{
      id: string;
      storage_key: string;
      storage_provider: string;
      content_length: string;
      content_type: string | null;
      digest_sha256: string | null;
      metadata: Record<string, unknown>;
      created_at: Date;
    }>(
      `SELECT id, storage_key, storage_provider, content_length, content_type,
              digest_sha256, metadata, created_at
       FROM wfos_artifact_metadata WHERE id = $1`,
      [id],
    );
    if (result.rows.length === 0) return null;
    return this.mapRow(result.rows[0]!);
  }

  private mapRow(row: {
    id: string;
    storage_key: string;
    storage_provider: string;
    content_length: string;
    content_type: string | null;
    digest_sha256: string | null;
    metadata: Record<string, unknown>;
    created_at: Date;
  }): ArtifactMetadata {
    return {
      id: row.id,
      storageKey: row.storage_key,
      storageProvider: row.storage_provider,
      contentLength: Number(row.content_length),
      contentType: row.content_type,
      digestSha256: row.digest_sha256,
      metadata: row.metadata ?? {},
      createdAt: row.created_at,
    };
  }
}
