import type { HostConformanceFixture } from '../types.js';

/**
 * V2-004 — the exported cross-host protocol conformance fixtures.
 *
 * Each fixture pairs host-class ADVERTISEMENTS (what a real host of that
 * platform class registers through the protocol) with one REQUIREMENT SET
 * and the EXPECTED eligibility outcomes. The suite
 * tests/unit/node-capability/conformance-fixtures.test.ts drives every
 * fixture through the REAL service (real HMAC registration path,
 * deterministic injected clock) and asserts the expected outcomes — so the
 * fixtures are executable shared conformance data, not prose.
 *
 * Consumable by:
 *   - future host implementations (web/desktop/ios/android/cloud) to verify
 *     their advertisement/matching behavior against the same contract;
 *   - IG-002 (WorkflowIR ↔ capability/placement integration), which reuses
 *     these requirement sets and expected outcomes for IR compatibility.
 *
 * Authorization discrimination is deliberately NOT modeled here: the
 * fixtures cover only the dimensions this protocol owns (protocol,
 * capability, placement, trust, health). Authorization is an explicit
 * separate dimension decided outside the node+capability protocol (see
 * tests/unit/node-capability/capability-vs-authorization.test.ts for the
 * discrimination regression).
 */

const HEALTHY = { supportsHumanApproval: false, health: 'healthy' as const };

export const NODE_CAPABILITY_CONFORMANCE_FIXTURES: readonly HostConformanceFixture[] = [
  {
    id: 'V2-004-FIX-01-cloud-workflow-github',
    description: 'cloud-required workflow+github capability set resolves only on the cloud host',
    keySeed: 'v2-004-fix-01',
    advertisements: [
      {
        id: 'cloud-01',
        platformClass: 'cloud',
        protocolVersion: 1,
        capabilities: [
          { name: 'workflow.execute', version: 1, availability: 'available' },
          { name: 'workflow.observe', version: 1, availability: 'available' },
          { name: 'github.repository.read', version: 1, availability: 'available' },
          { name: 'github.pull_request.create', version: 1, availability: 'available' },
          { name: 'github.pull_request.merge', version: 1, availability: 'available' },
        ],
        attributes: HEALTHY,
        trustTier: 'trusted',
        heartbeatAgeMs: 0,
      },
      {
        id: 'web-01',
        platformClass: 'web',
        protocolVersion: 1,
        capabilities: [
          { name: 'browser.navigate', version: 1, availability: 'available' },
          { name: 'browser.click', version: 1, availability: 'available' },
          { name: 'browser.observe', version: 1, availability: 'available' },
          { name: 'notifications.observe', version: 1, availability: 'available' },
        ],
        attributes: HEALTHY,
        trustTier: 'trusted',
        heartbeatAgeMs: 0,
      },
    ],
    requirementSet: {
      id: 'FIX-01-REQ',
      capabilities: [{ name: 'workflow.execute' }, { name: 'github.pull_request.create' }],
      placement: { required: 'cloud_required' },
    },
    expectedOutcomes: [
      {
        nodeAdvertisementId: 'cloud-01',
        eligible: true,
        protocolEligible: true,
        capabilityEligible: true,
        placementEligible: true,
        trustEligible: true,
        healthEligible: true,
        placementRank: 0,
        reasonCodes: [],
      },
      {
        nodeAdvertisementId: 'web-01',
        eligible: false,
        protocolEligible: true,
        capabilityEligible: false,
        placementEligible: false,
        trustEligible: true,
        healthEligible: true,
        placementRank: null,
        reasonCodes: [
          'CAPABILITY_NOT_ADVERTISED',
          'CAPABILITY_NOT_ADVERTISED',
          'PLACEMENT_CLASS_MISMATCH',
        ],
      },
    ],
  },
  {
    id: 'V2-004-FIX-02-cross-surface-browser-observe',
    description: 'the same browser.observe requirement resolves equivalently on web and desktop host classes',
    keySeed: 'v2-004-fix-02',
    advertisements: [
      {
        id: 'web-01',
        platformClass: 'web',
        protocolVersion: 1,
        capabilities: [
          { name: 'browser.observe', version: 2, availability: 'available' },
          { name: 'browser.navigate', version: 1, availability: 'available' },
        ],
        attributes: { supportsHumanApproval: true, health: 'healthy' },
        trustTier: 'trusted',
        heartbeatAgeMs: 0,
      },
      {
        id: 'desktop-01',
        platformClass: 'desktop',
        protocolVersion: 1,
        capabilities: [
          { name: 'browser.observe', version: 2, availability: 'available' },
          { name: 'filesystem.read', version: 1, availability: 'available' },
          { name: 'ui.inspect', version: 1, availability: 'available' },
        ],
        attributes: HEALTHY,
        trustTier: 'trusted',
        heartbeatAgeMs: 0,
      },
    ],
    requirementSet: {
      id: 'FIX-02-REQ',
      capabilities: [{ name: 'browser.observe', minVersion: 2 }],
      placement: { required: 'any_supported_node' },
    },
    expectedOutcomes: [
      {
        nodeAdvertisementId: 'web-01',
        eligible: true,
        protocolEligible: true,
        capabilityEligible: true,
        placementEligible: true,
        trustEligible: true,
        healthEligible: true,
        placementRank: 0,
        reasonCodes: [],
      },
      {
        nodeAdvertisementId: 'desktop-01',
        eligible: true,
        protocolEligible: true,
        capabilityEligible: true,
        placementEligible: true,
        trustEligible: true,
        healthEligible: true,
        placementRank: 0,
        reasonCodes: [],
      },
    ],
    crossSurfaceEquivalence: { a: 'web-01', b: 'desktop-01' },
  },
  {
    id: 'V2-004-FIX-03-phone-messaging-device-local',
    description: 'device_local messaging capability resolves on the android host; the cloud host is explicitly ineligible',
    keySeed: 'v2-004-fix-03',
    advertisements: [
      {
        id: 'android-01',
        platformClass: 'android',
        protocolVersion: 1,
        capabilities: [
          { name: 'phone.call.answer', version: 1, availability: 'available' },
          { name: 'messaging.send', version: 1, availability: 'available' },
          { name: 'contacts.read', version: 1, availability: 'available' },
        ],
        attributes: { supportsHumanApproval: true, health: 'healthy' },
        trustTier: 'trusted',
        heartbeatAgeMs: 0,
      },
      {
        id: 'cloud-01',
        platformClass: 'cloud',
        protocolVersion: 1,
        capabilities: [
          { name: 'workflow.execute', version: 1, availability: 'available' },
          { name: 'github.repository.read', version: 1, availability: 'available' },
        ],
        attributes: HEALTHY,
        trustTier: 'trusted',
        heartbeatAgeMs: 0,
      },
    ],
    requirementSet: {
      id: 'FIX-03-REQ',
      capabilities: [{ name: 'messaging.send' }],
      placement: { required: 'device_local' },
    },
    expectedOutcomes: [
      {
        nodeAdvertisementId: 'android-01',
        eligible: true,
        protocolEligible: true,
        capabilityEligible: true,
        placementEligible: true,
        trustEligible: true,
        healthEligible: true,
        placementRank: 0,
        reasonCodes: [],
      },
      {
        nodeAdvertisementId: 'cloud-01',
        eligible: false,
        protocolEligible: true,
        capabilityEligible: false,
        placementEligible: false,
        trustEligible: true,
        healthEligible: true,
        placementRank: null,
        reasonCodes: ['CAPABILITY_NOT_ADVERTISED', 'PLACEMENT_LOCALITY_VIOLATION'],
      },
    ],
  },
  {
    id: 'V2-004-FIX-04-privacy-local-only',
    description: 'local-only privacy constraint excludes the cloud host even though the placement chain would allow it',
    keySeed: 'v2-004-fix-04',
    advertisements: [
      {
        id: 'web-01',
        platformClass: 'web',
        protocolVersion: 1,
        capabilities: [{ name: 'workflow.observe', version: 1, availability: 'available' }],
        attributes: HEALTHY,
        trustTier: 'trusted',
        heartbeatAgeMs: 0,
      },
      {
        id: 'cloud-01',
        platformClass: 'cloud',
        protocolVersion: 1,
        capabilities: [{ name: 'workflow.observe', version: 1, availability: 'available' }],
        attributes: HEALTHY,
        trustTier: 'trusted',
        heartbeatAgeMs: 0,
      },
    ],
    requirementSet: {
      id: 'FIX-04-REQ',
      capabilities: [{ name: 'workflow.observe' }],
      placement: { required: 'cloud_allowed' },
      privacy: { localOnly: true },
    },
    expectedOutcomes: [
      {
        nodeAdvertisementId: 'web-01',
        eligible: true,
        protocolEligible: true,
        capabilityEligible: true,
        placementEligible: true,
        trustEligible: true,
        healthEligible: true,
        placementRank: 0,
        reasonCodes: [],
      },
      {
        nodeAdvertisementId: 'cloud-01',
        eligible: false,
        protocolEligible: true,
        capabilityEligible: true,
        placementEligible: false,
        trustEligible: true,
        healthEligible: true,
        placementRank: null,
        reasonCodes: ['PRIVACY_LOCAL_ONLY_VIOLATION'],
      },
    ],
  },
  {
    id: 'V2-004-FIX-05-preferred-fallback-order',
    description: 'device_preferred with an explicit cloud fallback ranks device hosts first (deterministic ordering)',
    keySeed: 'v2-004-fix-05',
    advertisements: [
      {
        id: 'web-01',
        platformClass: 'web',
        protocolVersion: 1,
        capabilities: [{ name: 'workflow.observe', version: 1, availability: 'available' }],
        attributes: HEALTHY,
        trustTier: 'trusted',
        heartbeatAgeMs: 0,
      },
      {
        id: 'web-02',
        platformClass: 'web',
        protocolVersion: 1,
        capabilities: [{ name: 'workflow.observe', version: 1, availability: 'available' }],
        attributes: HEALTHY,
        trustTier: 'trusted',
        heartbeatAgeMs: 0,
      },
      {
        id: 'cloud-01',
        platformClass: 'cloud',
        protocolVersion: 1,
        capabilities: [{ name: 'workflow.observe', version: 1, availability: 'available' }],
        attributes: HEALTHY,
        trustTier: 'trusted',
        heartbeatAgeMs: 0,
      },
    ],
    requirementSet: {
      id: 'FIX-05-REQ',
      capabilities: [{ name: 'workflow.observe' }],
      placement: { required: 'device_preferred', fallbackOrder: ['cloud_allowed'] },
    },
    expectedOutcomes: [
      {
        nodeAdvertisementId: 'web-01',
        eligible: true,
        protocolEligible: true,
        capabilityEligible: true,
        placementEligible: true,
        trustEligible: true,
        healthEligible: true,
        placementRank: 0,
        reasonCodes: [],
      },
      {
        nodeAdvertisementId: 'web-02',
        eligible: true,
        protocolEligible: true,
        capabilityEligible: true,
        placementEligible: true,
        trustEligible: true,
        healthEligible: true,
        placementRank: 0,
        reasonCodes: [],
      },
      {
        nodeAdvertisementId: 'cloud-01',
        eligible: true,
        protocolEligible: true,
        capabilityEligible: true,
        placementEligible: true,
        trustEligible: true,
        healthEligible: true,
        // Admitted ONLY through the explicit declared fallback, at rank 1.
        placementRank: 1,
        reasonCodes: [],
      },
    ],
  },
  {
    id: 'V2-004-FIX-06-trust-health-separation',
    description: 'trust tier and heartbeat liveness fail as their OWN dimensions while capability possession stays eligible',
    keySeed: 'v2-004-fix-06',
    advertisements: [
      {
        id: 'cloud-provisional',
        platformClass: 'cloud',
        protocolVersion: 1,
        capabilities: [{ name: 'workflow.execute', version: 1, availability: 'available' }],
        attributes: HEALTHY,
        trustTier: 'provisional',
        heartbeatAgeMs: 0,
      },
      {
        id: 'cloud-stale',
        platformClass: 'cloud',
        protocolVersion: 1,
        capabilities: [{ name: 'workflow.execute', version: 1, availability: 'available' }],
        attributes: HEALTHY,
        trustTier: 'trusted',
        heartbeatAgeMs: 61_000, // past the default 60s lease
      },
    ],
    requirementSet: {
      id: 'FIX-06-REQ',
      capabilities: [{ name: 'workflow.execute' }],
      placement: { required: 'any_supported_node' },
      minTrustTier: 'trusted',
    },
    expectedOutcomes: [
      {
        nodeAdvertisementId: 'cloud-provisional',
        eligible: false,
        protocolEligible: true,
        capabilityEligible: true,
        placementEligible: true,
        trustEligible: false,
        healthEligible: true,
        placementRank: 0,
        reasonCodes: ['TRUST_TIER_BELOW_MINIMUM'],
      },
      {
        nodeAdvertisementId: 'cloud-stale',
        eligible: false,
        protocolEligible: true,
        capabilityEligible: true,
        placementEligible: true,
        trustEligible: true,
        healthEligible: false,
        placementRank: 0,
        reasonCodes: ['HEARTBEAT_STALE'],
      },
    ],
  },
  {
    id: 'V2-004-FIX-07-protocol-version-gate',
    description: 'a node below the requirement minimum protocol version is excluded (fail closed)',
    keySeed: 'v2-004-fix-07',
    supportedProtocolVersions: [1, 2],
    advertisements: [
      {
        id: 'cloud-v1',
        platformClass: 'cloud',
        protocolVersion: 1,
        capabilities: [{ name: 'workflow.observe', version: 1, availability: 'available' }],
        attributes: HEALTHY,
        trustTier: 'trusted',
        heartbeatAgeMs: 0,
      },
      {
        id: 'cloud-v2',
        platformClass: 'cloud',
        protocolVersion: 2,
        capabilities: [{ name: 'workflow.observe', version: 1, availability: 'available' }],
        attributes: HEALTHY,
        trustTier: 'trusted',
        heartbeatAgeMs: 0,
      },
    ],
    requirementSet: {
      id: 'FIX-07-REQ',
      capabilities: [{ name: 'workflow.observe' }],
      placement: { required: 'any_supported_node' },
      minProtocolVersion: 2,
    },
    expectedOutcomes: [
      {
        nodeAdvertisementId: 'cloud-v1',
        eligible: false,
        protocolEligible: false,
        capabilityEligible: true,
        placementEligible: true,
        trustEligible: true,
        healthEligible: true,
        placementRank: 0,
        reasonCodes: ['PROTOCOL_VERSION_UNSUPPORTED'],
      },
      {
        nodeAdvertisementId: 'cloud-v2',
        eligible: true,
        protocolEligible: true,
        capabilityEligible: true,
        placementEligible: true,
        trustEligible: true,
        healthEligible: true,
        placementRank: 0,
        reasonCodes: [],
      },
    ],
  },
  {
    id: 'V2-004-FIX-08-human-approval',
    description: 'a human-approval requirement admits only the host declaring an approval surface',
    keySeed: 'v2-004-fix-08',
    advertisements: [
      {
        id: 'web-01',
        platformClass: 'web',
        protocolVersion: 1,
        capabilities: [{ name: 'browser.observe', version: 1, availability: 'available' }],
        attributes: { supportsHumanApproval: true, health: 'healthy' },
        trustTier: 'trusted',
        heartbeatAgeMs: 0,
      },
      {
        id: 'cloud-01',
        platformClass: 'cloud',
        protocolVersion: 1,
        capabilities: [
          { name: 'browser.observe', version: 1, availability: 'available' },
          { name: 'workflow.execute', version: 1, availability: 'available' },
        ],
        attributes: HEALTHY,
        trustTier: 'trusted',
        heartbeatAgeMs: 0,
      },
    ],
    requirementSet: {
      id: 'FIX-08-REQ',
      capabilities: [{ name: 'browser.observe' }],
      placement: { required: 'any_supported_node' },
      humanApprovalRequired: true,
    },
    expectedOutcomes: [
      {
        nodeAdvertisementId: 'web-01',
        eligible: true,
        protocolEligible: true,
        capabilityEligible: true,
        placementEligible: true,
        trustEligible: true,
        healthEligible: true,
        placementRank: 0,
        reasonCodes: [],
      },
      {
        nodeAdvertisementId: 'cloud-01',
        eligible: false,
        protocolEligible: true,
        capabilityEligible: true,
        placementEligible: false,
        trustEligible: true,
        healthEligible: true,
        placementRank: null,
        reasonCodes: ['HUMAN_APPROVAL_NOT_SUPPORTED'],
      },
    ],
  },
  {
    id: 'V2-004-FIX-09-capability-version-availability',
    description: 'capability versioning and availability gate matching independently (explicit reasons, no substitution)',
    keySeed: 'v2-004-fix-09',
    advertisements: [
      {
        id: 'web-v3',
        platformClass: 'web',
        protocolVersion: 1,
        capabilities: [{ name: 'browser.navigate', version: 3, availability: 'available' }],
        attributes: HEALTHY,
        trustTier: 'trusted',
        heartbeatAgeMs: 0,
      },
      {
        id: 'web-degraded',
        platformClass: 'web',
        protocolVersion: 1,
        capabilities: [{ name: 'browser.navigate', version: 2, availability: 'degraded' }],
        attributes: HEALTHY,
        trustTier: 'trusted',
        heartbeatAgeMs: 0,
      },
      {
        id: 'web-old',
        platformClass: 'web',
        protocolVersion: 1,
        capabilities: [{ name: 'browser.navigate', version: 1, availability: 'available' }],
        attributes: HEALTHY,
        trustTier: 'trusted',
        heartbeatAgeMs: 0,
      },
    ],
    requirementSet: {
      id: 'FIX-09-REQ',
      capabilities: [{ name: 'browser.navigate', minVersion: 2 }],
      placement: { required: 'device_local' },
    },
    expectedOutcomes: [
      {
        nodeAdvertisementId: 'web-v3',
        eligible: true,
        protocolEligible: true,
        capabilityEligible: true,
        placementEligible: true,
        trustEligible: true,
        healthEligible: true,
        placementRank: 0,
        reasonCodes: [],
      },
      {
        nodeAdvertisementId: 'web-degraded',
        eligible: false,
        protocolEligible: true,
        capabilityEligible: false,
        placementEligible: true,
        trustEligible: true,
        healthEligible: true,
        placementRank: 0,
        reasonCodes: ['CAPABILITY_UNAVAILABLE'],
      },
      {
        nodeAdvertisementId: 'web-old',
        eligible: false,
        protocolEligible: true,
        capabilityEligible: false,
        placementEligible: true,
        trustEligible: true,
        healthEligible: true,
        placementRank: 0,
        reasonCodes: ['CAPABILITY_VERSION_BELOW_MINIMUM'],
      },
    ],
  },
];
