/**
 * Queue abstraction for WorkflowOS background workers.
 *
 * The frozen architecture mandates Redis-backed background workers for
 * long-running work (PLAT-001 / PLAT-AC-03). This interface is the shared
 * boundary that:
 *
 * - domain code uses to enqueue jobs (API request → enqueue → return)
 * - the worker runtime uses to dequeue and acknowledge jobs
 *
 * Two implementations exist:
 *
 * - {@link InMemoryQueue} — in-process FIFO used for local dev and tests.
 * - {@link RedisQueue} — Redis-backed (RPUSH/LPOP, FIFO) used in production.
 *
 * Both satisfy the same interface, so the worker host and call sites remain
 * implementation-agnostic. Redis is the backing store for production; it is
 * NOT authoritative application state (architecture §29).
 */

/**
 * A unit of background work. The {@link JobRecord.executionId} carries the
 * traceable identifier required by OBS-AC-01 / OBS-AC-02.
 */
export interface JobRecord<TPayload = unknown> {
  /** Unique job id (generated by the queue). */
  readonly id: string;
  /** Job type, e.g. `echo` (fixture) or future `github.webhook`, `llm.request`. */
  readonly type: string;
  /** Opaque job payload. */
  readonly payload: TPayload;
  /** Traceable execution identifier carried API → queue → worker → logs. */
  readonly executionId: string;
  /** Optional correlation id linking related jobs. Defaults to executionId. */
  readonly correlationId?: string;
  /** Epoch milliseconds when the job was enqueued. */
  readonly enqueuedAt: number;
}

export interface EnqueueOptions {
  /**
   * Traceable execution id. When omitted, the queue generates one so every
   * enqueued job carries OBS-AC-01 traceability even if the caller had no
   * active context.
   */
  executionId?: string;
  /** Optional correlation id; defaults to the (resolved) execution id. */
  correlationId?: string;
}

/**
 * Background job queue. Implementations MUST be non-blocking on `enqueue`
 * (the API request path returns as soon as the job is persisted to the
 * queue) and SHOULD be non-blocking on `dequeue` (return `null` when empty
 * so the worker host can poll without busy-spinning).
 */
export interface Queue {
  /** Persist a job and return its record. Must NOT block on execution. */
  enqueue<T>(type: string, payload: T, options?: EnqueueOptions): Promise<JobRecord<T>>;
  /** Remove and return the next pending job, or `null` when the queue is empty. */
  dequeue(): Promise<JobRecord | null>;
  /** Acknowledge successful (or failed-but-handled) processing of a job. */
  ack(jobId: string): Promise<void>;
  /** Current number of pending jobs. */
  size(): Promise<number>;
  /** Release resources held by the queue. */
  close(): Promise<void>;
}
